### ISSUE TITLE
Add links to rules

### ISSUE THREAD

**Issue by amilajack** [jfmengels/eslint-plugin-fp#2]
Eslint supports linking to documentation for rules. For example, if the `no-comma-dangle` fails, it will return a link to the rule:

https://github.com/AtomLinter/linter-eslint/wiki/Linking-to-Rule-Documentation

**Comment by jfmengels** [comment]
Hi @amilajack!

That's not an ESLint feature, that is a feature of the Atom linter plugin.
I recently created a new repo that has that same list (https://github.com/jfmengels/eslint-rule-documentation/) and I'm working on integrating it in that plugin (https://github.com/AtomLinter/linter-eslint/pull/657), though I'll have to get back to working on that. Obviously, this plugin is already on that new list, so it just needs to be merged.

Thanks for the reporting this though :)
