### ISSUE TITLE
no-mutating-assign with any expression

### ISSUE THREAD

**Issue by benadamstyles** [jfmengels/eslint-plugin-fp#42]
Thanks for this excellent plugin. Further to #17, I wonder if you'd consider allowing any function call as the first argument to `Object.assign()` (or at least add an option to allow this). For example, I think this would always be "functionally safe":

```js
Object.assign(anyFunctionCall(_), {prop: 'value'})
```

If you're happy with the concept I'm happy to PR (although any hint you can give about what the eslint `type` of a function call would be, would be very helpful, as I've never written an eslint rule before)!

**Comment by graingert** [comment]
not safe:

```js
const globalObj = {};
globalObj.prop; // undefined
const anyFunctionCall = () => globalObj;
const newObj = Object.assign(anyFunctionCall(_), {prop: 'value'});
newObj.value; // 'value'
globalObj.prop; // 'value'
```

**Comment by graingert** [comment]
safe:
```js
const globalObj = {};
globalObj.prop; // undefined
const anyFunctionCall = () => globalObj;
const newObj = Object.assign({}, anyFunctionCall(_), {prop: 'value'});
newObj.value; // 'value'
globalObj.prop; // undefined

**Comment by benadamstyles** [comment]
Yep my mistake!
