### ISSUE TITLE
(fp/no-nil) rule for callbacks?

### ISSUE THREAD

**Issue by Dylanb-dev** [jfmengels/eslint-plugin-fp#43]
It is standard to write callbacks with error first so you end up with `callback(null, "success message")` or `callback(err)`.

Is the solution to get around this to not use callbacks?

**Comment by graingert** [comment]
?

**Comment by graingert** [comment]
oh yes, you can't use callbacks because by their nature they're not pure

**Comment by Dylanb-dev** [comment]
Yeah just a lot of code has this convention and wanted the ruling on it. 

I will try to use promises instead of callbacks.

**Comment by graingert** [comment]
I'd recommend using some effects library like Monet or IxJS then converting to a promise or continuation passing API at the last possible moment.

**Comment by graingert** [comment]
promises are also impure!

**Comment by Dylanb-dev** [comment]
Yeah I have separated side effects from my functions in my codebase but at the end it has a callback.
