### ISSUE TITLE
ESLint v6

### ISSUE THREAD

**Issue by ronanyeah** [jfmengels/eslint-plugin-fp#51]
Based on a quick check this plugin doesn't appear to be working with the new ESLint. Can look into it further later, just opening an issue to track it.

https://eslint.org/docs/6.0.0/user-guide/migrating-to-6.0.0

**Comment by ronanyeah** [comment]
```
$ eslint .

Oops! Something went wrong! :(

ESLint: 6.0.1.

ESLint couldn't find the plugin "eslint-plugin-fp".

(The package "eslint-plugin-fp" was not found when loaded as a Node module from the directory "/home/ronan/repos/drivesheet".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-fp@latest --save-dev

The plugin "eslint-plugin-fp" was referenced from the config file in "PersonalConfig".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by ronanyeah** [comment]
I've gotten it semi working so will close for now, may reopen.

**Comment by k-yle** [comment]
Hey @ronanyeah, how did you resolve this? I'm having the same issue now that [react-scripts](https://npm.im/react-scripts) has updated eslint to v6.

**Comment by ronanyeah** [comment]
I'm using a global eslint install and I install plugins into a specific folder. These are my Neovim ale settings:
`let g:ale_javascript_eslint_options = "--config ~/Documents/eslint/.eslintrc.js --resolve-plugins-relative-to ~/Documents/eslint"`
