### ISSUE TITLE
Definition for rule 'fp/no-arguments' was not found

### ISSUE THREAD

**Issue by joshburgess** [jfmengels/eslint-plugin-fp#6]
I've got the latest version and all seems to be working well except for this. Is this definition not in the latest version of the npm package yet?

**Comment by jfmengels** [comment]
You're right, I hadn't publish yet.

I just published v2.1.0 where it should be available, along with `no-rest-parameters`.

**Comment by joshburgess** [comment]
Sorry, hadn't checked the closed issues! :P

**Comment by jfmengels** [comment]
Easy mistake to make :smile:
